[package]
name = "webAssembly-learn"
version = "1.0.0"
description = ""
license = "ISC"

[dependencies]
"_/cowsay" = "0.2.0"

[[module]]
name = "add"
source = "./wasm/program.wasm"
abi = "emscripten"

[[command]]
name = "add"
module = "add"
